# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d1be784a3d2c2c56ff66f86f6717d7b2a18d850705000b7835bc46ec12b3d2225450d79266c78609841d6fdc9e53d328ce66dbbc020e8b6e0964dd6360c1747b

test:
  secret_key_base: 2070b4017f6653a218f089733cc2832763987072ba460ef2fcce719c235b6c8de518f96c68cc40fb49a1623efabe5dbb81a13fca2d21e5c42e4396ab4d6cc372

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
